### ISSUE TITLE
Missing file in the dataset downloaded from the given website.

### ISSUE THREAD

**Issue by Liu-Xinhang** [ApoorvaBeedu/VideoPose#1]
I downloaded the YCBV dataset from the website, but it says that i miss some file ending with '-posecnn.mat' like "000647-posecnn.mat". Did I miss something in the downloading progress?

**Comment by ApoorvaBeedu** [comment]
Hi, 
No, I manually created those files using the posecnn implementation. Branch v1 should work without those files.
