### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/YCB_Video_Dataset/classes.txt'

### ISSUE THREAD

**Issue by ZJU-PLP** [ApoorvaBeedu/VideoPose#2]
@ApoorvaBeedu 
Hi, dear author:
    I find that the YCB dataset is different from PoseCNN [download link](https://rse-lab.cs.washington.edu/projects/posecnn/) in format. Could you mind sharing the details how to generate train.txt, keyframe.txt, val.txt ?
**Your YCB dataset format:**
![image](https://user-images.githubusercontent.com/32757213/206636769-fe2eb291-46bf-472b-8952-99364253985c.png)
**PoseCNN YCB dataset format:**
![image](https://user-images.githubusercontent.com/32757213/206637157-6ec7602e-4de2-44a2-84f7-a56eef182b48.png)

**Comment by ApoorvaBeedu** [comment]
Hello, Sorry for the delay in response.
You should be able to find those files within image_sets.

**Comment by ZJU-PLP** [comment]
> image_sets

Okkk, thanks for yor reply.

**Comment by ZJU-PLP** [comment]
@ApoorvaBeedu 
How can I get points1.xyz? YCB_Video_Dataset only has points.xyz in models document.

![image](https://user-images.githubusercontent.com/32757213/206901413-a034d9a3-8384-4b20-b865-e74fffb6df84.png)
![image](https://user-images.githubusercontent.com/32757213/206901444-a378eaa3-e439-43b2-8137-e6851188e7bd.png)

**Comment by ApoorvaBeedu** [comment]
You should be able to run the files with dense=False flag. 
But [here](https://drive.google.com/drive/folders/1xQVD4G5wZ0-JvHYkNxIsw3B-d0CILCSO?usp=sharing) are the files.

**Comment by ZJU-PLP** [comment]
> You should be able to run the files with dense=False flag. But [here](https://drive.google.com/drive/folders/1xQVD4G5wZ0-JvHYkNxIsw3B-d0CILCSO?usp=sharing) are the files.

Ok, thanks for your reply again.
