### ISSUE TITLE
Cannot run train_eval.py by Execution command

### ISSUE THREAD

**Issue by ZJU-PLP** [ApoorvaBeedu/VideoPose#3]
@ApoorvaBeedu 
Hi, I meet one problem by running command bash `python3 train_eval.py --batch_size=8 --lr=0.0001 --backbone=swin --predict_future=1 --use_depth=1 --video_length=5 --workers=1 --restore_file=videopose`. Could you mind offering the advice to solve this problem?
I debug and find that this problem exists [here](https://github.com/ApoorvaBeedu/VideoPose/blob/v1/models/trainer.py#L410). However, I don't know how to solve it.

![image](https://user-images.githubusercontent.com/32757213/206956860-293240ae-b5c2-439e-95b3-a49876950d49.png)
[debug.log](https://github.com/ApoorvaBeedu/VideoPose/files/10204447/debug.log)
[debug-internal.log](https://github.com/ApoorvaBeedu/VideoPose/files/10204448/debug-internal.log)

**Comment by W-QY** [comment]
Hi, could you please explain to me the meaning of "v1 is the branch to use."? Because I currently do not have a "- posecnn. mat" file.

**Comment by ZJU-PLP** [comment]
> Hi, could you please explain to me the meaning of "v1 is the branch to use."? Because I currently do not have a "- posecnn. mat" file.

Yes, v1 is branch v1.

**Comment by W-QY** [comment]
I'm very happy to see your reply, but I still don't know what branch v1 is and how to use it

**Comment by W-QY** [comment]
> > Hi, could you please explain to me the meaning of "v1 is the branch to use."? Because I currently do not have a "- posecnn. mat" file.
> 
> Yes, v1 is branch v1.

I'm very happy to see your reply, but I still don't know what branch v1 is and how to use it

**Comment by ZJU-PLP** [comment]
> > > Hi, could you please explain to me the meaning of "v1 is the branch to use."? Because I currently do not have a "- posecnn. mat" file.
> > 
> > 
> > Yes, v1 is branch v1.
> 
> I'm very happy to see your reply, but I still don't know what branch v1 is and how to use it

You can switch the branch to v1 and follow the step README of here.
![image](https://user-images.githubusercontent.com/32757213/207829534-976ba1f0-e3e8-4996-8329-b5856842f62d.png)
![image](https://user-images.githubusercontent.com/32757213/207830121-8fbb7d96-a251-46b9-9be0-65b9e32507ae.png)

**Comment by W-QY** [comment]
> > > > Hi, could you please explain to me the meaning of "v1 is the branch to use."? Because I currently do not have a "- posecnn. mat" file.
> > > 
> > > 
> > > Yes, v1 is branch v1.
> > 
> > 
> > I'm very happy to see your reply, but I still don't know what branch v1 is and how to use it
> 
> You can switch the branch to v1 and follow the step README of here. ![image](https://user-images.githubusercontent.com/32757213/207829534-976ba1f0-e3e8-4996-8329-b5856842f62d.png) ![image](https://user-images.githubusercontent.com/32757213/207830121-8fbb7d96-a251-46b9-9be0-65b9e32507ae.png)

Thanks a million！！！

**Comment by ApoorvaBeedu** [comment]
@ZJU-PLP I am not sure what the error could be. What GPU are you using? 
Also, could you please debug within the forward loop?  The code runs fine for me still.

**Comment by ZJU-PLP** [comment]
@ApoorvaBeedu Thanks for your reply. 
Do you run the version of V1?

My GPU version is NVIDIA GTX1080Ti and my PyTorch Version is 1.7. 
I have debuged within the forward loop and find the error is in [this line](https://github.com/ApoorvaBeedu/VideoPose/blob/v1/models/model.py#L322-L323). However, I have tested the ops.roi_align API and find it can be run ok separately.

**Comment by ZJU-PLP** [comment]
@ApoorvaBeedu I have debuged within the forward loop again and find the error is in [this line](https://github.com/ApoorvaBeedu/VideoPose/blob/v1/models/model.py#L326). However, I have tested the backbone API and find it can be run ok separately.

[SwinModel Test Example](https://huggingface.co/docs/transformers/model_doc/swin):
```
from transformers import AutoImageProcessor, SwinModel
import torch
from datasets import load_dataset

dataset = load_dataset("huggingface/cats-image")
image = dataset["test"]["image"][0]

image_processor = AutoImageProcessor.from_pretrained("microsoft/swin-tiny-patch4-window7-224")
model = SwinModel.from_pretrained("microsoft/swin-tiny-patch4-window7-224")

inputs = image_processor(image, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state
list(last_hidden_states.shape)
>>> [1, 49, 768]
```
output:
![image](https://user-images.githubusercontent.com/32757213/218682694-56f0ef41-a679-4c95-aaa5-3c55c4b76218.png)

**Comment by ZJU-PLP** [comment]
@ApoorvaBeedu I have found the pytorch version must be >= 1.12, the error will be fixed. Furthermore, I have tested different pytorch version (including 1.7, 1.9, 1.10) and the error will occur.
