### ISSUE TITLE
How to split train and eval process?

### ISSUE THREAD

**Issue by ZJU-PLP** [ApoorvaBeedu/VideoPose#4]
@ApoorvaBeedu 
Hi, dear author:

　I cannot find the pretrained model and  eval process from your README. Could you mind reorganizing README and providing eval bash command?

**Comment by ApoorvaBeedu** [comment]
Hi, sorry for the delay in response. 

Please find the updated readme instructions in commit 70e67fc.
Eval is done using the keyframes. I still generate videos, but make sure the "keyframe" is present as the last frame.

**Comment by ZJU-PLP** [comment]
@ApoorvaBeedu Thanks for updating. 
1. Can I understand that the command **Execution** `python3 train_eval.py --batch_size=8 --lr=0.0001 --backbone=swin --predict_future=1 --use_depth=1 --video_length=5 --workers=12` is training process and **Evaluation** `python3 train_eval.py --batch_size=8 --backbone=swin --predict_future=1 --use_depth=1 --video_length=5 --workers=12  --restore_file=Videopose --split=eval` is testing process?
2. Could you mind offering the **-posecnn.mat files** or offering the script to generating them?
