### ISSUE TITLE
Con you provide pretrained model?

### ISSUE THREAD

**Issue by ZJU-PLP** [ApoorvaBeedu/VideoPose#6]
@ApoorvaBeedu 
Hi, could you mind sharing the trained model to reproduce your nice work? If possible, can you also provide the script code to get ADD-S and ADD(S) in your eval code?

I have trained your published code in my computer over one week. However,  I have test the trained model and find the experiment results are very poor.
**My trained model:(trained 18 epoches)**
![image](https://github.com/ApoorvaBeedu/VideoPose/assets/32757213/4a4c462c-23ba-4eba-b22d-c6108179bdec)
**Visualizing results:**
![image](https://github.com/ApoorvaBeedu/VideoPose/assets/32757213/8be02f8c-d367-4d63-9a33-baf05866a42d)

![image](https://github.com/ApoorvaBeedu/VideoPose/assets/32757213/c15499f1-a93d-44ae-97aa-128068787dbc)

**Comment by wetoo-cando** [comment]
As mentioned in the "Setting up dataset" section of the README, a checkpoint is available at https://drive.google.com/drive/folders/1lQh3G7KN-SHb7B-NYpqWj55O1WD4E9s6?usp=sharing

However, I get an error when using it 
`python3 train_eval.py --batch_size=8 --backbone=swin --predict_future=1 --use_depth=1 --video_length=5 --workers=12  --restore_file=Videopose --split=eval`

`RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        Unexpected key(s) in state_dict: "module.gru.gru.h.0.attn.bias", "module.gru.gru.h.0.attn.masked_bias", "module.gru.gru.h.1.attn.bias", "module.gru.gru.h.1.attn.masked_bias", "module.gru.gru.h.2.attn.bias", "module.gru.gru.h.2.attn.masked_bias", "module.gru.gru.h.3.attn.bias", "module.gru.gru.h.3.attn.masked_bias". `

**Comment by ApoorvaBeedu** [comment]
@wetoo-cando I believe the GPT in huggingface has evolved since I have used it. I unfortunately do not remember what version it was. Probably 4.16 or earlier.
